.\"
.\" Copyright (c) 2021 Scott Bennett <scottb@fastmail.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd June 15, 2021
.Dt GOTIME 8
.Os
.Sh NAME
.Nm gotime
.Nd simple Daytime Protocol daemon
.Sh SYNOPSIS
.Nm gotime
.Op Fl d
.Sh DESCRIPTION
.Nm
is a privilege-dropping server that implements the Daytime Protocol as specified in
RFC 867.
It responds to TCP connections on port
.Em 13 ,
returns a human-readable date string to the client,
then closes the connection.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl d
Do not daemonize.
.Nm
will run in the foreground and output debug messages to stdout.
.El
.Pp
In debug mode
.Pq Fl d ,
root privileges are not required for startup and the server will listen on
.Em localhost
port
.Em 13013 .
.Sh BUILD
To build
.Nm :
.Pp
.Dl $ make
.Pp
To clean things up:
.Pp
.Dl $ make clean
.Pp
To install, first create the necessary user account, then install the program:
.Bd -literal -offset indent
# make user
# make install
.Ed
.Sh AUTHORS
.An Scott Bennett
.Sh CAVEATS
.Nm
has only been built and tested on
.Ox 6.8
or newer, because it relies on
.Xr pledge 2 .
